export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-container": "#00eefc",
        "on-tertiary-fixed-variant": "#6d0061",
        "surface-bright": "#2b2c2e",
        "error-dim": "#d7383b",
        "on-background": "#ffffff",
        "on-secondary-container": "#f8f1ff",
        "tertiary-fixed-dim": "#ff68e3",
        "surface-container-low": "#121315",
        "surface-container": "#181a1b",
        "tertiary": "#ff59e3",
        "on-secondary-fixed-variant": "#6300e2",
        "on-tertiary-fixed": "#33002d",
        "tertiary-dim": "#ff59e3",
        "error-container": "#9f0519",
        "inverse-surface": "#fbf9fa",
        "outline-variant": "#474849",
        "secondary-container": "#7000ff",
        "on-primary-fixed": "#003f43",
        "on-primary-container": "#005359",
        "inverse-on-surface": "#555556",
        "on-primary": "#005d63",
        "on-error-container": "#ffa8a3",
        "error": "#ff716c",
        "secondary-dim": "#874cff",
        "outline": "#757576",
        "surface-dim": "#0d0e0f",
        "primary-fixed": "#00eefc",
        "surface-variant": "#242627",
        "on-tertiary-container": "#1b0017",
        "on-surface-variant": "#ababac",
        "surface": "#0d0e0f",
        "primary": "#8ff5ff",
        "primary-fixed-dim": "#00deec",
        "secondary-fixed": "#dac9ff",
        "on-error": "#490006",
        "on-secondary-fixed": "#41009a",
        "on-secondary": "#290067",
        "surface-container-highest": "#242627",
        "surface-container-high": "#1e2021",
        "surface-container-lowest": "#000000",
        "secondary": "#ac89ff",
        "inverse-primary": "#006a71",
        "primary-dim": "#00deec",
        "on-surface": "#ffffff",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-container": "#ff05e5",
        "surface-tint": "#8ff5ff",
        "background": "#0d0e0f",
        "secondary-fixed-dim": "#ceb9ff",
        "on-tertiary": "#42003a",
        "tertiary-fixed": "#ff85e4"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
